# Path: configs/example_config.yaml

dlc_config: /path/to/your/dlc/config.yaml

behaviors: # list of behavior labels
  - string

features:
  ref_pt: keypoint_1 # keypoint to use as origin for relative position
  body_length_pts: # keypoints to use for calculating the body length (for scaling)
    - keypoint_1
    - keypoint_2
  distances: # list of 2-element lists
    - [keypoint_1, keypoint_2]
  angles: # list of 3-element lists
    - [keypoint_1, keypoint_2, keypoint_3]

window:
  size: 60
  stride: 10

training:
  batch_size: 8
  model:
    variant: bilstm
  epochs: 10
  learning_rate: 0.001
  include_absolute_coordinates: false
  loss: focal
  val_fraction: 0.1
  seed: 100
  reduce_lr: true
  early_stopping: true
  early_stopping_patience: 3
  early_stopping_min_delta: 0.0
  keypoint_noise_std:
    string: 0.01
  final_zero_fill: false
  focal:
    alpha:
      string: 0.7
    gamma: 2.0
