dlc_config: /path/to/your/dlc/config.yaml

behaviors: # list of behavior labels
  - string

features:
  ref_pt: keypoint_1 # keypoint to use as origin for relative position
  body_length_pts: # keypoints to use for calculating the body length (for scaling)
    - keypoint_1
    - keypoint_2
  distances: # list of 2-element lists
    - [keypoint_1, keypoint_2]
  angles: # list of 3-element lists
    - [keypoint_1, keypoint_2, keypoint_3]
